export const config = {
  model: 'cloudflare/clef-flash',
  provider: 'Cloudflare',
  decisionsUrl: 'https://openrouter.ai/api/alpha/decisions',
  host: '127.0.0.1',
  port: 4317,
  dbHost: '127.0.0.1',
  dbPort: 5547,
  importer: { user: 'importer', password: 'local-import-only' },
  database: 'olist',
  statementTimeoutMs: 5000,
  decisionTimeoutMs: 45000,
  maxQuestionBytes: 1200,
  maxConcurrentRequests: 2,
  offerLimit: 200,
  offerTtlMs: 30 * 60 * 1000,
  datasetCacheMs: 5 * 60 * 1000,
  datasetUrl: 'https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce',
};
